BEGIN;

ALTER TABLE redes
  ADD COLUMN IF NOT EXISTS cnpj TEXT,
  ADD COLUMN IF NOT EXISTS email_contato TEXT,
  ADD COLUMN IF NOT EXISTS telefone TEXT,
  ADD COLUMN IF NOT EXISTS ativa BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS valor_implantacao NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_mensalidade NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS primeiro_cobranca DATE,
  ADD COLUMN IF NOT EXISTS dia_cobranca INT;

CREATE UNIQUE INDEX IF NOT EXISTS uq_redes_cnpj ON redes (cnpj) WHERE cnpj IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_redes_nome_fantasia_lower ON redes ((LOWER(nome_fantasia)));

ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS telefone TEXT;

COMMIT;
